name: Taurus - Performance Testing

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies for Taurus
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade wheel setuptools Cython
        pip install bzt
    - name: Running taurus yaml file for testing
      uses: Rbillon59/taurus-action@v0.1-beta
      with:
        taurus_project_folder_name: 'taurus-scenario'
        taurus_command_line: taurus-scenario.yaml -report

